preset: laravel

risky: false

disabled:
  - concat_without_spaces
  - phpdoc_to_comment
  - phpdoc_var_without_name

enabled:
  - concat_with_spaces
  - phpdoc_annotation_without_dot

finder:
  exclude:
  - "tests"
